"""create all tables

Revision ID: ae8e902705b1
Revises: 
Create Date: 2023-06-13 21:23:39.185706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8e902705b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('waiters',
    sa.Column('waiter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('waiter_id')
    )
    op.create_table('tables',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('start_armor', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_armor', sa.TIMESTAMP(), nullable=True),
    sa.Column('waiter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['waiter'], ['waiters.waiter_id'], ),
    sa.PrimaryKeyConstraint('table_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables')
    op.drop_table('waiters')
    op.drop_table('message')
    # ### end Alembic commands ###
