"""Create table waiter

Revision ID: 532fd3389500
Revises: 
Create Date: 2023-06-06 16:54:47.441662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532fd3389500'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiters',
    sa.Column('waiter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('waiter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waiters')
    # ### end Alembic commands ###
