"""add column ager

Revision ID: 3f89c630d401
Revises: 64965ea2d58f
Create Date: 2023-06-01 21:49:05.666144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f89c630d401'
down_revision = '64965ea2d58f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waiters', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waiters', 'age')
    # ### end Alembic commands ###
