"""Create waiter  model

Revision ID: 64965ea2d58f
Revises: 
Create Date: 2023-06-01 21:44:29.115464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64965ea2d58f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiters',
    sa.Column('waiter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('waiter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waiters')
    # ### end Alembic commands ###
